### ISSUE TITLE
ImportError: cannot import name 'RigidBodyTree'

### ISSUE THREAD

**Issue by xman236** [HarvardAgileRoboticsLab/gym-drake#2]
After following the installation instructions, I try to run the example script (random.agent.py).
However, I somehow get the error shown below "ImportError: cannot import name 'RigidBodyTree'". Is there anything that I am missing here?

```
(my_venv) ralph@ralph-Precision-7740:~/gym-drake$ python3 random_agent.py 
INFO: Making new env: DrakeCartpoleMBP-v0
Traceback (most recent call last):
  File "random_agent.py", line 27, in <module>
    env = gym.make(args.env_id)
  File "/home/ralph/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/ralph/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/ralph/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/ralph/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ralph/gym-drake/gym_drake/envs/__init__.py", line 2, in <module>
    from gym_drake.envs.rigid_body_tree_env import RigidBodyTreeEnv
  File "/home/ralph/gym-drake/gym_drake/envs/rigid_body_tree_env.py", line 3, in <module>
    from pydrake.all import RigidBodyTree, RigidBodyPlant, AddModelInstanceFromUrdfFile, FloatingBaseType
ImportError: cannot import name 'RigidBodyTree'
```

**Comment by pvarin** [comment]
It’s been forever since I’ve revisited this code but it’s possible
(probable) that Drake no longer supports RigidBodyTree. Or maybe it’s
somewhere in pydrake.attic.

**Comment by xman236** [comment]
I see. By any chance, do you know any project/ repo that has done Reinforcement Learning based on Drake? 


> It’s been forever since I’ve revisited this code but it’s possible
> (probable) that Drake no longer supports RigidBodyTree. Or maybe it’s
> somewhere in pydrake.attic.

**Comment by pvarin** [comment]
Not off the top of my head sorry :/ I know of one other project but they
also used RigidBodyTree. It probably wouldn’t be too much work to
cannibalize this repo to use MultiBodyPlant. Or to just roll out your own
openai-gym environment.
